### ISSUE TITLE
Exception on Initializing EULAPage 

### ISSUE THREAD

**Issue by tariqhusein** [DevExpress-Examples/xamarin-forms-stocks-app#1]
{System.TypeLoadException: Invalid type Stocks.UI.Views.BarIconItem for instance field Stocks.UI.Views.TitleView:menuItem
  at Stocks.UI.Views.EULAPage..ctor () [0x00009] in ..\xamarin-forms-stocks-app-20.1.1-\CS\Stocks.UI\Views\EULAPage.xaml.cs:9 }

**Comment by DmitryRomenskiy** [comment]
Hello @tariqhusein,

Please accept my apologies for the late reply. We recommend contacting our technical support via the [Support Center](https://supportcenter.devexpress.com/ticket/list) to resolve technical issues. If you still encounter this error, feel free to create a ticket there.
