### ISSUE TITLE
DevExpress.XamarinForms.DemoEditors

### ISSUE THREAD

**Issue by Luvnet-890** [DevExpress-Examples/xamarin-forms-stocks-app#2]
Latest code base is using DevExpress.XamarinForms.DemoEditors. Can you please build the code with the latest DevExpress versions to DevExpress.XamarinForms.Editors.
Also if we can update the code with all latest packages would help as well.

Thanks in advance

**Comment by DmitryRomenskiy** [comment]
Hello @Luvnet-890,

Thank you for pointing this out and please accept my apologies for the late reply. Currently, we cannot make a simple change and migrate this example to the required package. However, we will consider ways to do that in the future.
